All stories tab - add category
JSTech2020/groups_de pull request #38
Opened 2020-04-16 16:03 UTC by klarmannsonia

In this PR:
- restructure code to functional components
- added category filter for all stories tab
- change story card list for dynamic content

![image](https://user-images.githubusercontent.com/29261118/79478933-ae49e100-8014-11ea-8478-b44491b0ac84.png)

2020-04-16 20:12 UTC, ahmad-diaa commented on frontend-zs/src/components/stories/StoryList.js
> +        let allCategories = []
```suggestion
        let distinctCategories = new Set()
```
We could create the set directly and change it into a list a the end, instead going through all this conversions list->set->list

2020-04-16 21:21 UTC, ahmad-diaa commented on frontend-zs/src/components/stories/StoryCard.js
> +                        {story.categories.map((category) => {
Can we just use `story.categories.toString()` here instead?

2020-04-16 21:26 UTC, ahmad-diaa requested changes
Can we have a default category place holder (i.e "Categories: None") to avoid the nonalignment of cards in case a card does not have a category?

2020-04-16 23:00 UTC, daliamaarek commented on frontend-zs/src/components/stories/StoryCard.js
> +        <Card className="mb-4">
Every card should have a unique key in the list, this could be the title or even the index of the card in the list 

```suggestion
        <Card className="mb-4" key={story.title}>
```

2020-04-16 23:00 UTC, daliamaarek commented on frontend-zs/src/components/stories/StoryCard.js
> +                            if (category == story.categories.slice(-1).pop())
I think you forgot that extra equal sign 😄 

```suggestion
                            if (category === story.categories.slice(-1).pop())
```

2020-04-16 23:00 UTC, daliamaarek commented on frontend-zs/src/components/stories/StoryCard.js
> +export default function StoryCarsList(stories) {
Typo: I believe you meant `StoryCardList`

2020-04-16 23:00 UTC, daliamaarek commented on frontend-zs/src/components/stories/StoryFilter.js
> +        <ToggleButton value={category} className="btn-category mr-2" >
I think you need to add a key for each category button in the category list as well

2020-04-16 23:00 UTC, daliamaarek commented on frontend-zs/src/components/stories/StoryFilter.js
> +    const handleChange = (selected) => {
There's something weird when I enable and disable a category filter, the button is sometimes still selected (it doesn't toggle between yellow/white yet the filter works properly) 

Does this actually happen or is it just me for some reason? 😅

2020-04-17 01:50 UTC, ahmad-diaa commented on frontend-zs/src/components/stories/StoryList.js
> +        setDisplayCategories(distinctCategories)
```suggestion
        let distinctCategories = new Set(stories.flatMap(story=> {
               return story.categories
        })
        setDisplayCategories([...distinctCategories])
```
We could create the set directly and change it into a list a the end, instead going through all this conversions list->set->list

Also, I think it is a better practice to use a value returning method with the map function.

2020-04-17 12:08 UTC, klarmannsonia commented on frontend-zs/src/components/stories/StoryCard.js
> +                            if (category == story.categories.slice(-1).pop())
Changed this to story,categories.toString() as Ahmad mentioned.

2020-04-17 12:11 UTC, klarmannsonia commented
> Can we have a default category place holder (i.e "Categories: None") to avoid the nonalignment of cards in case a card does not have a category?

Fixed this by checking if there is a category or not.

![image](https://user-images.githubusercontent.com/29261118/79567861-95e1d100-80bd-11ea-883f-a093798d04a0.png)

2020-04-17 12:15 UTC, klarmannsonia commented on frontend-zs/src/components/stories/StoryFilter.js
> +    const handleChange = (selected) => {
This also happens to me when switching to tablet mode in developer tool. I am not sure if this will happen when using a real tablet.

2020-04-17 13:11 UTC, klarmannsonia commented on frontend-zs/src/components/stories/StoryFilter.js
> +    const handleChange = (selected) => {
This doesn't happen when using Mozilla Firefox.

2020-04-17 13:30 UTC, daliamaarek approved these changes

2020-04-17 13:53 UTC, ahmad-diaa commented
> > Can we have a default category place holder (i.e "Categories: None") to avoid the nonalignment of cards in case a card does not have a category?
> 
> Fixed this by checking if there is a category or not.
> 
> ![image](https://user-images.githubusercontent.com/29261118/79567861-95e1d100-80bd-11ea-883f-a093798d04a0.png)

This is not what I meant, you can see in the second screenshot that the card on the right is not aligned with the card on the left because they do not have the same height.

2020-04-17 14:11 UTC, klarmannsonia commented
> > > Can we have a default category place holder (i.e "Categories: None") to avoid the nonalignment of cards in case a card does not have a category?
> > 
> > 
> > Fixed this by checking if there is a category or not.
> > ![image](https://user-images.githubusercontent.com/29261118/79567861-95e1d100-80bd-11ea-883f-a093798d04a0.png)
> 
> This is not what I meant, you can see in the second screenshot that the card on the right is not aligned with the card on the left because they do not have the same height.

I don't understand where you mean that they are not aligned. The cards won't have the same size, because the short description will be different. This is why I used CardColumns to align them according to different heights.

2020-04-17 14:20 UTC, ahmad-diaa commented
> This is not what I meant, you can see in the second screenshot that the card on the right is not aligned with the card on the left because they do not have the same height.

Okay, this makes sense. I just think that we need to add a validation on the shortDescription length to avoid cards with too long description messing the view

2020-04-17 14:22 UTC, ahmad-diaa approved these changes

2020-04-17 14:22 UTC, klarmannsonia commented
> > This is not what I meant, you can see in the second screenshot that the card on the right is not aligned with the card on the left because they do not have the same height.
> 
> Okay, this makes sense. I just think that we need to add a validation on the shortDescription length to avoid cards with too long description messing the view

I will ask Felix about the length of the short description and if he has, some examples.

2020-04-17 14:25 UTC, ahmad-diaa commented
> I will ask Felix about the length of the short description and if he has, some examples.
We can merge this PR anyways, as this should be accounted for in the create story view.

2020-04-17 14:26 UTC, merged