Feature/17 project feed
JSTech2020/groups_de pull request #61
Opened 2020-04-27 13:27 UTC by daliamaarek

In this PR: 
* New Post UI  
* Users can upload images
* Posts for a project are displayed
* I also added Sonia's PrivateRoute fix just so we could directly merge when we've merged her stuff (Hope that's okay) 

In upcoming PR:
* Backend should be implemented and integrated (get images from bucket,as well as post Post)

<img width="382" alt="Screen Shot 2020-04-27 at 3 20 33 PM" src="https://user-images.githubusercontent.com/10801286/80377014-f251a700-889a-11ea-8b2f-5738151c57d7.png">

2020-04-28 06:49 UTC, klarmannsonia requested changes

2020-04-28 06:49 UTC, klarmannsonia commented on frontend-zs/src/components/projects/SingleProject/Feed.js
> +                            onChange={evt => handleImagesChange(evt)}
When I upload a media, the text "Upload a photo" doesn't change. I was not sure if the picture I selected was taken or not. Is it just on my computer for some reason? If not, can we take the picture name as the label text?

2020-04-28 06:49 UTC, klarmannsonia commented on frontend-zs/src/components/projects/SingleProject/Feed.js
> +                        <Button className="mt-md-3 float-right" size="sm" onClick={() => handleSubmit()}>Submit</Button>
Can this button have the same size as the Browse button?

2020-04-28 06:49 UTC, klarmannsonia commented on frontend-zs/src/App.js
> +            <Route path="/stories" component={StoryList} />
`StoryList` should also have a `PrivateRoute`

2020-04-29 07:54 UTC, klarmannsonia approved these changes

2020-04-29 15:29 UTC, ahmad-diaa approved these changes

2020-04-29 15:30 UTC, merged